steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia.gcr.io/discord-bot-308317/sushanshan",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/discord-bot-308317/sushanshan"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "sushanshan",
        "--image",
        "asia.gcr.io/discord-bot-308317/sushanshan",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
      ]
images:
  - asia.gcr.io/discord-bot-308317/sushanshan
timeout: 1200s
